# Generated by Django 4.0.4 on 2022-06-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='text', max_length=100)),
                ('model', models.TextField(help_text='Enter short description')),
                ('system', models.CharField(default='text', max_length=100)),
                ('memory', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
