# Generated by Django 4.0.4 on 2022-07-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0002_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phone',
            name='picture',
            field=models.ImageField(blank=True, upload_to='picture/%y/%m/%d/'),
        ),
    ]
